server:
  port: 8080

spring:
  application:
    name: spring-boot-starter-app

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.app: DEBUG
