package db

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// DeployRequest is one row of the deployment center's request ledger: a
// proposal to promote a branch/SHA of a project to an environment. The
// lifecycle moves through status transitions guarded by
// UpdateDeployRequestStatus (CAS). At most one request per
// (workspace, project) may be in an in-flight status
// (pending_approval/approved/deploying) — enforced by the partial unique
// index uq_deploy_requests_inflight.
type DeployRequest struct {
	ID          string            `json:"id"`
	WorkspaceID string            `json:"workspace_id"`
	ProjectID   string            `json:"project_id"`
	Branch      string            `json:"branch"`
	SHA         string            `json:"sha"`
	Env         string            `json:"env"`
	Vars        map[string]string `json:"vars"`
	CommitSpan  []CommitSpanEntry `json:"commitSpan"`
	Approval    map[string]any    `json:"approval"`
	Status      string            `json:"status"`
	PipelineID  int64             `json:"pipeline_id"`
	Health      map[string]any    `json:"health"`
	CreatedBy   string            `json:"created_by"`
	CreatedAt   string            `json:"created_at"`
	StartedAt   string            `json:"started_at"`
	FinishedAt  string            `json:"finished_at"`
}

// CommitSpanEntry describes one commit covered by a deploy request.
type CommitSpanEntry struct {
	SHA         string `json:"sha"`
	ShortSHA    string `json:"shortSha"`
	Title       string `json:"title"`
	Author      string `json:"author"`
	CommittedAt string `json:"committedAt"`
}

// DeployRequestFilter narrows ListDeployRequests. Empty fields are ignored.
type DeployRequestFilter struct {
	WorkspaceID string
	ProjectID   string
	Status      string
	Limit       int
}

func marshalDeployRequestJSON(v any, fallback string) (string, error) {
	if v == nil {
		return fallback, nil
	}
	b, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// InsertDeployRequest persists a new deploy request. The ID is generated by
// the caller ("dep-" + hex short id style); CreatedAt defaults to nowUTC()
// when empty.
func (db *SQLiteStore) InsertDeployRequest(req DeployRequest) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in InsertDeployRequest: %v", r)
		}
	}()
	if req.ID == "" {
		return fmt.Errorf("deploy request requires an id")
	}
	if req.WorkspaceID == "" || req.ProjectID == "" || req.Status == "" {
		return fmt.Errorf("deploy request requires workspace, project and status")
	}
	if req.Env == "" {
		req.Env = "production"
	}
	if req.CreatedAt == "" {
		req.CreatedAt = nowUTC()
	}
	varsJSON, err := marshalDeployRequestJSON(req.Vars, "{}")
	if err != nil {
		return fmt.Errorf("marshal deploy request vars: %w", err)
	}
	commitSpanJSON, err := marshalDeployRequestJSON(req.CommitSpan, "[]")
	if err != nil {
		return fmt.Errorf("marshal deploy request commit span: %w", err)
	}
	approvalJSON, err := marshalDeployRequestJSON(req.Approval, "{}")
	if err != nil {
		return fmt.Errorf("marshal deploy request approval: %w", err)
	}
	healthJSON, err := marshalDeployRequestJSON(req.Health, "{}")
	if err != nil {
		return fmt.Errorf("marshal deploy request health: %w", err)
	}
	_, err = db.sql.Exec(`INSERT INTO deploy_requests (
	id, workspace_id, project_id, branch, sha, env, vars_json, commit_span_json,
	approval_json, status, pipeline_id, health_json, created_by, created_at,
	started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		req.ID, req.WorkspaceID, req.ProjectID, req.Branch, req.SHA, req.Env,
		varsJSON, commitSpanJSON, approvalJSON, req.Status, req.PipelineID,
		healthJSON, req.CreatedBy, req.CreatedAt, req.StartedAt, req.FinishedAt)
	return err
}

// DeployRequestFor returns the request by id, or (nil, false, nil) when it
// does not exist — callers must treat "no request" as fail-closed.
func (db *SQLiteStore) DeployRequestFor(workspaceID, id string) (req *DeployRequest, found bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in DeployRequestFor: %v", r)
		}
	}()
	workspaceID = strings.TrimSpace(workspaceID)
	id = strings.TrimSpace(id)
	if workspaceID == "" || id == "" {
		return nil, false, nil
	}
	row := db.sql.QueryRow(`SELECT id, workspace_id, project_id, branch, sha, env,
	vars_json, commit_span_json, approval_json, status, pipeline_id, health_json,
	created_by, created_at, started_at, finished_at
	FROM deploy_requests WHERE workspace_id = ? AND id = ?`, workspaceID, id)
	r, err := scanDeployRequest(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return &r, true, nil
}

// ListDeployRequests returns requests matching the non-empty filter fields,
// newest first, optionally capped by Limit.
func (db *SQLiteStore) ListDeployRequests(filter DeployRequestFilter) (list []DeployRequest, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in ListDeployRequests: %v", r)
		}
	}()
	query := `SELECT id, workspace_id, project_id, branch, sha, env,
	vars_json, commit_span_json, approval_json, status, pipeline_id, health_json,
	created_by, created_at, started_at, finished_at
	FROM deploy_requests WHERE 1=1`
	var args []any
	if filter.WorkspaceID != "" {
		query += " AND workspace_id = ?"
		args = append(args, filter.WorkspaceID)
	}
	if filter.ProjectID != "" {
		query += " AND project_id = ?"
		args = append(args, filter.ProjectID)
	}
	if filter.Status != "" {
		query += " AND status = ?"
		args = append(args, filter.Status)
	}
	query += " ORDER BY created_at DESC"
	if filter.Limit > 0 {
		query += fmt.Sprintf(" LIMIT %d", filter.Limit)
	}
	rows, err := db.sql.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []DeployRequest
	for rows.Next() {
		r, err := scanDeployRequest(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, r)
	}
	return result, rows.Err()
}

// LatestSucceededDeployRequest returns the most recent status='success'
// request for the project, or (nil, false, nil) when none exists.
func (db *SQLiteStore) LatestSucceededDeployRequest(workspaceID, projectID string) (req *DeployRequest, found bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in LatestSucceededDeployRequest: %v", r)
		}
	}()
	workspaceID = strings.TrimSpace(workspaceID)
	projectID = strings.TrimSpace(projectID)
	if workspaceID == "" || projectID == "" {
		return nil, false, nil
	}
	row := db.sql.QueryRow(`SELECT id, workspace_id, project_id, branch, sha, env,
	vars_json, commit_span_json, approval_json, status, pipeline_id, health_json,
	created_by, created_at, started_at, finished_at
	FROM deploy_requests
	WHERE workspace_id = ? AND project_id = ? AND status = 'success'
	ORDER BY created_at DESC LIMIT 1`, workspaceID, projectID)
	r, err := scanDeployRequest(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return &r, true, nil
}

// UpdateDeployRequestStatus performs a CAS status transition: the row is
// updated only when its current status equals `from`. Returns true when
// exactly one row transitioned.
func (db *SQLiteStore) UpdateDeployRequestStatus(workspaceID, id, from, to string) (ok bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in UpdateDeployRequestStatus: %v", r)
		}
	}()
	workspaceID = strings.TrimSpace(workspaceID)
	id = strings.TrimSpace(id)
	if workspaceID == "" || id == "" || from == "" || to == "" {
		return false, fmt.Errorf("deploy request status transition requires workspace, id, from and to")
	}
	res, err := db.sql.Exec(`UPDATE deploy_requests SET status = ?
	WHERE workspace_id = ? AND id = ? AND status = ?`, to, workspaceID, id, from)
	if err != nil {
		return false, err
	}
	affected, err := res.RowsAffected()
	if err != nil {
		return false, err
	}
	return affected == 1, nil
}

// SetDeployRequestPipeline records the CI pipeline id that materialized the
// deployment.
func (db *SQLiteStore) SetDeployRequestPipeline(workspaceID, id string, pipelineID int64) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in SetDeployRequestPipeline: %v", r)
		}
	}()
	workspaceID = strings.TrimSpace(workspaceID)
	id = strings.TrimSpace(id)
	if workspaceID == "" || id == "" {
		return fmt.Errorf("deploy request pipeline update requires workspace and id")
	}
	_, err = db.sql.Exec(`UPDATE deploy_requests SET pipeline_id = ?
	WHERE workspace_id = ? AND id = ?`, pipelineID, workspaceID, id)
	return err
}

// SetDeployRequestHealth replaces the health snapshot of a request.
func (db *SQLiteStore) SetDeployRequestHealth(workspaceID, id string, health map[string]any) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in SetDeployRequestHealth: %v", r)
		}
	}()
	workspaceID = strings.TrimSpace(workspaceID)
	id = strings.TrimSpace(id)
	if workspaceID == "" || id == "" {
		return fmt.Errorf("deploy request health update requires workspace and id")
	}
	healthJSON, err := marshalDeployRequestJSON(health, "{}")
	if err != nil {
		return fmt.Errorf("marshal deploy request health: %w", err)
	}
	_, err = db.sql.Exec(`UPDATE deploy_requests SET health_json = ?
	WHERE workspace_id = ? AND id = ?`, healthJSON, workspaceID, id)
	return err
}

// HasApprovedDeployRequestForSHA reports whether the SHA already has a
// request in an approved-or-beyond state (approved/deploying/success) — used
// to fail closed against duplicate deployments of the same commit.
func (db *SQLiteStore) HasApprovedDeployRequestForSHA(workspaceID, projectID, sha string) (found bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in HasApprovedDeployRequestForSHA: %v", r)
		}
	}()
	workspaceID = strings.TrimSpace(workspaceID)
	projectID = strings.TrimSpace(projectID)
	sha = strings.TrimSpace(sha)
	if workspaceID == "" || projectID == "" || sha == "" {
		return false, nil
	}
	var one int
	err = db.sql.QueryRow(`SELECT 1 FROM deploy_requests
	WHERE workspace_id = ? AND project_id = ? AND sha = ?
	  AND status IN ('approved','deploying','success') LIMIT 1`,
		workspaceID, projectID, sha).Scan(&one)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

// ListDeployingDeployRequests returns every request currently in status
// 'deploying' across all workspaces (startup self-healing scans these).
func (db *SQLiteStore) ListDeployingDeployRequests() (list []DeployRequest, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic in ListDeployingDeployRequests: %v", r)
		}
	}()
	rows, err := db.sql.Query(`SELECT id, workspace_id, project_id, branch, sha, env,
	vars_json, commit_span_json, approval_json, status, pipeline_id, health_json,
	created_by, created_at, started_at, finished_at
	FROM deploy_requests WHERE status = 'deploying' ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []DeployRequest
	for rows.Next() {
		r, err := scanDeployRequest(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, r)
	}
	return result, rows.Err()
}

type deployRequestScanner interface {
	Scan(dest ...any) error
}

func scanDeployRequest(s deployRequestScanner) (DeployRequest, error) {
	var r DeployRequest
	var varsJSON, commitSpanJSON, approvalJSON, healthJSON string
	err := s.Scan(
		&r.ID,
		&r.WorkspaceID,
		&r.ProjectID,
		&r.Branch,
		&r.SHA,
		&r.Env,
		&varsJSON,
		&commitSpanJSON,
		&approvalJSON,
		&r.Status,
		&r.PipelineID,
		&healthJSON,
		&r.CreatedBy,
		&r.CreatedAt,
		&r.StartedAt,
		&r.FinishedAt,
	)
	if err != nil {
		return DeployRequest{}, err
	}
	if varsJSON != "" {
		if err := json.Unmarshal([]byte(varsJSON), &r.Vars); err != nil {
			return DeployRequest{}, fmt.Errorf("unmarshal deploy request vars: %w", err)
		}
	}
	if commitSpanJSON != "" {
		if err := json.Unmarshal([]byte(commitSpanJSON), &r.CommitSpan); err != nil {
			return DeployRequest{}, fmt.Errorf("unmarshal deploy request commit span: %w", err)
		}
	}
	if approvalJSON != "" {
		if err := json.Unmarshal([]byte(approvalJSON), &r.Approval); err != nil {
			return DeployRequest{}, fmt.Errorf("unmarshal deploy request approval: %w", err)
		}
	}
	if healthJSON != "" {
		if err := json.Unmarshal([]byte(healthJSON), &r.Health); err != nil {
			return DeployRequest{}, fmt.Errorf("unmarshal deploy request health: %w", err)
		}
	}
	return r, nil
}
